// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: internal/proto/event.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamEventsRequest contains the parameters for subscribing to events
type StreamEventsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChainId         int32                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	EventSignature  string                 `protobuf:"bytes,3,opt,name=event_signature,json=eventSignature,proto3" json:"event_signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_internal_proto_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_event_proto_rawDescGZIP(), []int{0}
}

func (x *StreamEventsRequest) GetChainId() int32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *StreamEventsRequest) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *StreamEventsRequest) GetEventSignature() string {
	if x != nil {
		return x.EventSignature
	}
	return ""
}

// GetEventsRequest contains the parameters for retrieving events
type GetEventsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChainId         int32                  `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	TxHash          string                 `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"` // Optional
	Take            int32                  `protobuf:"varint,4,opt,name=take,proto3" json:"take,omitempty"`                  // Optional, default 10
	Skip            int32                  `protobuf:"varint,5,opt,name=skip,proto3" json:"skip,omitempty"`                  // Optional, default 0
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	mi := &file_internal_proto_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_event_proto_rawDescGZIP(), []int{1}
}

func (x *GetEventsRequest) GetChainId() int32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetEventsRequest) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *GetEventsRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *GetEventsRequest) GetTake() int32 {
	if x != nil {
		return x.Take
	}
	return 0
}

func (x *GetEventsRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

// GetEventsResponse contains a list of events and pagination info
type GetEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*EventData           `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsResponse) Reset() {
	*x = GetEventsResponse{}
	mi := &file_internal_proto_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsResponse) ProtoMessage() {}

func (x *GetEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsResponse.ProtoReflect.Descriptor instead.
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_event_proto_rawDescGZIP(), []int{2}
}

func (x *GetEventsResponse) GetData() []*EventData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetEventsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// EventData represents a blockchain event with additional metadata
type EventData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	BlockNumber     int64                  `protobuf:"varint,3,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	TxHash          string                 `protobuf:"bytes,4,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	LogIndex        int32                  `protobuf:"varint,5,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
	Data            string                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EventData) Reset() {
	*x = EventData{}
	mi := &file_internal_proto_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventData) ProtoMessage() {}

func (x *EventData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventData.ProtoReflect.Descriptor instead.
func (*EventData) Descriptor() ([]byte, []int) {
	return file_internal_proto_event_proto_rawDescGZIP(), []int{3}
}

func (x *EventData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventData) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *EventData) GetBlockNumber() int64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *EventData) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *EventData) GetLogIndex() int32 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

func (x *EventData) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *EventData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// Pagination contains pagination information
type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skip          int32                  `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Take          int32                  `protobuf:"varint,2,opt,name=take,proto3" json:"take,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_internal_proto_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_internal_proto_event_proto_rawDescGZIP(), []int{4}
}

func (x *Pagination) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *Pagination) GetTake() int32 {
	if x != nil {
		return x.Take
	}
	return 0
}

// Event represents a blockchain event
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber   int64                  `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	TxHash        string                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_internal_proto_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_internal_proto_event_proto_rawDescGZIP(), []int{5}
}

func (x *Event) GetBlockNumber() int64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *Event) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *Event) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_internal_proto_event_proto protoreflect.FileDescriptor

const file_internal_proto_event_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/proto/event.proto\x12\teventpool\"\x84\x01\n" +
	"\x13StreamEventsRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x05R\achainId\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12'\n" +
	"\x0fevent_signature\x18\x03 \x01(\tR\x0eeventSignature\"\x99\x01\n" +
	"\x10GetEventsRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x05R\achainId\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\tR\x06txHash\x12\x12\n" +
	"\x04take\x18\x04 \x01(\x05R\x04take\x12\x12\n" +
	"\x04skip\x18\x05 \x01(\x05R\x04skip\"t\n" +
	"\x11GetEventsResponse\x12(\n" +
	"\x04data\x18\x01 \x03(\v2\x14.eventpool.EventDataR\x04data\x125\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x15.eventpool.PaginationR\n" +
	"pagination\"\xd2\x01\n" +
	"\tEventData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12!\n" +
	"\fblock_number\x18\x03 \x01(\x03R\vblockNumber\x12\x17\n" +
	"\atx_hash\x18\x04 \x01(\tR\x06txHash\x12\x1b\n" +
	"\tlog_index\x18\x05 \x01(\x05R\blogIndex\x12\x12\n" +
	"\x04data\x18\x06 \x01(\tR\x04data\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"4\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\x05R\x04skip\x12\x12\n" +
	"\x04take\x18\x02 \x01(\x05R\x04take\"W\n" +
	"\x05Event\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x03R\vblockNumber\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\tR\x06txHash\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data2\x9e\x01\n" +
	"\fEventService\x12D\n" +
	"\fStreamEvents\x12\x1e.eventpool.StreamEventsRequest\x1a\x10.eventpool.Event\"\x000\x01\x12H\n" +
	"\tGetEvents\x12\x1b.eventpool.GetEventsRequest\x1a\x1c.eventpool.GetEventsResponse\"\x00B\x12Z\x10event-pool/protob\x06proto3"

var (
	file_internal_proto_event_proto_rawDescOnce sync.Once
	file_internal_proto_event_proto_rawDescData []byte
)

func file_internal_proto_event_proto_rawDescGZIP() []byte {
	file_internal_proto_event_proto_rawDescOnce.Do(func() {
		file_internal_proto_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_event_proto_rawDesc), len(file_internal_proto_event_proto_rawDesc)))
	})
	return file_internal_proto_event_proto_rawDescData
}

var file_internal_proto_event_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_proto_event_proto_goTypes = []any{
	(*StreamEventsRequest)(nil), // 0: eventpool.StreamEventsRequest
	(*GetEventsRequest)(nil),    // 1: eventpool.GetEventsRequest
	(*GetEventsResponse)(nil),   // 2: eventpool.GetEventsResponse
	(*EventData)(nil),           // 3: eventpool.EventData
	(*Pagination)(nil),          // 4: eventpool.Pagination
	(*Event)(nil),               // 5: eventpool.Event
}
var file_internal_proto_event_proto_depIdxs = []int32{
	3, // 0: eventpool.GetEventsResponse.data:type_name -> eventpool.EventData
	4, // 1: eventpool.GetEventsResponse.pagination:type_name -> eventpool.Pagination
	0, // 2: eventpool.EventService.StreamEvents:input_type -> eventpool.StreamEventsRequest
	1, // 3: eventpool.EventService.GetEvents:input_type -> eventpool.GetEventsRequest
	5, // 4: eventpool.EventService.StreamEvents:output_type -> eventpool.Event
	2, // 5: eventpool.EventService.GetEvents:output_type -> eventpool.GetEventsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_proto_event_proto_init() }
func file_internal_proto_event_proto_init() {
	if File_internal_proto_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_event_proto_rawDesc), len(file_internal_proto_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_event_proto_goTypes,
		DependencyIndexes: file_internal_proto_event_proto_depIdxs,
		MessageInfos:      file_internal_proto_event_proto_msgTypes,
	}.Build()
	File_internal_proto_event_proto = out.File
	file_internal_proto_event_proto_goTypes = nil
	file_internal_proto_event_proto_depIdxs = nil
}
