server:
  port: 8080
  host: "0.0.0.0"

database:
  url: "postgresql://postgres:postgres@postgres:5432/event_pool_1?schema=public"

redis:
  addr: "redis:6379"
  password: ""
  db: 0

ethereum:
  chains:
    2484:
      rpc_url: "https://rpc-nebulas-testnet.u2u.xyz"
      block_time: 5 # seconds
    39:
      rpc_url: "https://rpc-mainnet.u2u.xyz"
      block_time: 1 # seconds

mqtt:
  broker_url: "tcp://mqtt:1883"
  client_id: "event-pool-server"
  username: ""
  password: ""
  qos: 1
  clean_session: false
  ping_interval: 30s
  connect_timeout: 10s

asynq:
  redis_addr: "redis:6379"
  concurrency: 10 