server:
  port: 8080
  host: "0.0.0.0"

database:
  url: "postgresql://postgres:postgres@postgres:5432/event_pool_1?schema=public"

redis:
  addr: "redis:6379"
  password: ""
  db: 0

ethereum:
  chains:
    2484:
      rpc_url: "https://rpc-nebulas-testnet.u2u.xyz"
      block_time: 5 # seconds
    39:
      rpc_url: "https://rpc-mainnet.u2u.xyz"
      block_time: 1 # seconds

mqtt:
  broker_url: "tcp://mqtt:1883"
  client_id: "event-pool-server"
  username: ""
  password: ""
  qos: 1
  clean_session: false
  ping_interval: 30s
  connect_timeout: 10s

asynq:
  redis_addr: "redis:6379"
  concurrency: 10

node_chain:
  name: "event_pool"
  params:
    config:
      chain_ids: [2484, 39]
      whitelists:
        deployment: ["0x21e185f9bAD13646205Db4BA6Eb9cCB885e447A1", "0x2743eEC46576f76f47334569074242F3D9a90B44"]
  genesis:
  bootnodes:
    - "/ip4/127.0.0.1/tcp/10006/p2p/16Uiu2HAkwTeJQzMwzSgLDnifn71B4c4DQaKbLSvGAAa9vMbSR2h6"
grpc_addr: :10000
data_dir: ./data/tmp
jsonrpc_addr: :10002
