server:
  port: 8080
  host: "0.0.0.0"
  address: "http://127.0.0.1"

database:
  url: "postgresql://postgres:postgres@postgres:5432/event_pool_1?schema=public"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

ethereum:
  chains:
    2484:
      rpc_url: "https://rpc-nebulas-testnet.u2u.xyz"
      block_time: 5 # seconds
    39:
      rpc_url: "https://rpc-mainnet.u2u.xyz"
      block_time: 1 # seconds

grpc:
  port: 9090

asynq:
  redis_addr: "localhost:6379"
  concurrency: 10

consul:
  id: "node3"
  host: "localhost"
  port: 8500
  service_id: "blockchain-node"
  health_check:
    port: 8080
    path: "/health"
    interval: "10s"
    timeout: "5s"


node_chain:
  name: "event_pool"
  params:
    config:
      chain_ids: [2484, 39]
      whitelists:
        deployment: ["0x21e185f9bAD13646205Db4BA6Eb9cCB885e447A1", "0x2743eEC46576f76f47334569074242F3D9a90B44"]
  genesis:
  bootnodes:
    - "/ip4/127.0.0.1/tcp/10006/p2p/16Uiu2HAkwTeJQzMwzSgLDnifn71B4c4DQaKbLSvGAAa9vMbSR2h6"
grpc_addr: :10000
jsonrpc_addr: :10002
data_dir: ./data/temp
