// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: txpool/proto/operator.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	// For initially added transactions
	EventType_ADDED EventType = 0
	// For enqueued transactions in the account queue
	EventType_ENQUEUED EventType = 1
	// For promoted transactions
	EventType_PROMOTED EventType = 2
	// For dropped transactions
	EventType_DROPPED EventType = 3
	// For demoted transactions
	EventType_DEMOTED EventType = 4
	// For pruned promoted transactions
	EventType_PRUNED_PROMOTED EventType = 5
	// For pruned enqueued transactions
	EventType_PRUNED_ENQUEUED EventType = 6
	// For subgraph events
	EventType_SUBGRAPH_EVENT_ADDED EventType = 7
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "ADDED",
		1: "ENQUEUED",
		2: "PROMOTED",
		3: "DROPPED",
		4: "DEMOTED",
		5: "PRUNED_PROMOTED",
		6: "PRUNED_ENQUEUED",
		7: "SUBGRAPH_EVENT_ADDED",
	}
	EventType_value = map[string]int32{
		"ADDED":                0,
		"ENQUEUED":             1,
		"PROMOTED":             2,
		"DROPPED":              3,
		"DEMOTED":              4,
		"PRUNED_PROMOTED":      5,
		"PRUNED_ENQUEUED":      6,
		"SUBGRAPH_EVENT_ADDED": 7,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_txpool_proto_operator_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_txpool_proto_operator_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_txpool_proto_operator_proto_rawDescGZIP(), []int{0}
}

type AddTxnReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTxnReq) Reset() {
	*x = AddTxnReq{}
	mi := &file_txpool_proto_operator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTxnReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTxnReq) ProtoMessage() {}

func (x *AddTxnReq) ProtoReflect() protoreflect.Message {
	mi := &file_txpool_proto_operator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTxnReq.ProtoReflect.Descriptor instead.
func (*AddTxnReq) Descriptor() ([]byte, []int) {
	return file_txpool_proto_operator_proto_rawDescGZIP(), []int{0}
}

func (x *AddTxnReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *AddTxnReq) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

type AddTxnResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=txHash,proto3" json:"txHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTxnResp) Reset() {
	*x = AddTxnResp{}
	mi := &file_txpool_proto_operator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTxnResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTxnResp) ProtoMessage() {}

func (x *AddTxnResp) ProtoReflect() protoreflect.Message {
	mi := &file_txpool_proto_operator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTxnResp.ProtoReflect.Descriptor instead.
func (*AddTxnResp) Descriptor() ([]byte, []int) {
	return file_txpool_proto_operator_proto_rawDescGZIP(), []int{1}
}

func (x *AddTxnResp) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type TxnPoolStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        uint64                 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnPoolStatusResp) Reset() {
	*x = TxnPoolStatusResp{}
	mi := &file_txpool_proto_operator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnPoolStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnPoolStatusResp) ProtoMessage() {}

func (x *TxnPoolStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_txpool_proto_operator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnPoolStatusResp.ProtoReflect.Descriptor instead.
func (*TxnPoolStatusResp) Descriptor() ([]byte, []int) {
	return file_txpool_proto_operator_proto_rawDescGZIP(), []int{2}
}

func (x *TxnPoolStatusResp) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Requested event types
	Types         []EventType `protobuf:"varint,1,rep,packed,name=types,proto3,enum=v1.EventType" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_txpool_proto_operator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_txpool_proto_operator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_txpool_proto_operator_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeRequest) GetTypes() []EventType {
	if x != nil {
		return x.Types
	}
	return nil
}

type TxPoolEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=v1.EventType" json:"type,omitempty"`
	TxHash        string                 `protobuf:"bytes,2,opt,name=txHash,proto3" json:"txHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxPoolEvent) Reset() {
	*x = TxPoolEvent{}
	mi := &file_txpool_proto_operator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxPoolEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxPoolEvent) ProtoMessage() {}

func (x *TxPoolEvent) ProtoReflect() protoreflect.Message {
	mi := &file_txpool_proto_operator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxPoolEvent.ProtoReflect.Descriptor instead.
func (*TxPoolEvent) Descriptor() ([]byte, []int) {
	return file_txpool_proto_operator_proto_rawDescGZIP(), []int{4}
}

func (x *TxPoolEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_ADDED
}

func (x *TxPoolEvent) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type SubscribePoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []EventType            `protobuf:"varint,1,rep,packed,name=types,proto3,enum=v1.EventType" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribePoolRequest) Reset() {
	*x = SubscribePoolRequest{}
	mi := &file_txpool_proto_operator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribePoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribePoolRequest) ProtoMessage() {}

func (x *SubscribePoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_txpool_proto_operator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribePoolRequest.ProtoReflect.Descriptor instead.
func (*SubscribePoolRequest) Descriptor() ([]byte, []int) {
	return file_txpool_proto_operator_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribePoolRequest) GetTypes() []EventType {
	if x != nil {
		return x.Types
	}
	return nil
}

type EventData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       string                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventData) Reset() {
	*x = EventData{}
	mi := &file_txpool_proto_operator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventData) ProtoMessage() {}

func (x *EventData) ProtoReflect() protoreflect.Message {
	mi := &file_txpool_proto_operator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventData.ProtoReflect.Descriptor instead.
func (*EventData) Descriptor() ([]byte, []int) {
	return file_txpool_proto_operator_proto_rawDescGZIP(), []int{6}
}

func (x *EventData) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type GossipRegisterContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipRegisterContractRequest) Reset() {
	*x = GossipRegisterContractRequest{}
	mi := &file_txpool_proto_operator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipRegisterContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipRegisterContractRequest) ProtoMessage() {}

func (x *GossipRegisterContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_txpool_proto_operator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipRegisterContractRequest.ProtoReflect.Descriptor instead.
func (*GossipRegisterContractRequest) Descriptor() ([]byte, []int) {
	return file_txpool_proto_operator_proto_rawDescGZIP(), []int{7}
}

func (x *GossipRegisterContractRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *GossipRegisterContractRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

type GossipRegisterContractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipRegisterContractResponse) Reset() {
	*x = GossipRegisterContractResponse{}
	mi := &file_txpool_proto_operator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipRegisterContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipRegisterContractResponse) ProtoMessage() {}

func (x *GossipRegisterContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_txpool_proto_operator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipRegisterContractResponse.ProtoReflect.Descriptor instead.
func (*GossipRegisterContractResponse) Descriptor() ([]byte, []int) {
	return file_txpool_proto_operator_proto_rawDescGZIP(), []int{8}
}

func (x *GossipRegisterContractResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_txpool_proto_operator_proto protoreflect.FileDescriptor

const file_txpool_proto_operator_proto_rawDesc = "" +
	"\n" +
	"\x1btxpool/proto/operator.proto\x12\x02v1\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"3\n" +
	"\tAddTxnReq\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\"$\n" +
	"\n" +
	"AddTxnResp\x12\x16\n" +
	"\x06txHash\x18\x01 \x01(\tR\x06txHash\"+\n" +
	"\x11TxnPoolStatusResp\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x04R\x06length\"7\n" +
	"\x10SubscribeRequest\x12#\n" +
	"\x05types\x18\x01 \x03(\x0e2\r.v1.EventTypeR\x05types\"H\n" +
	"\vTxPoolEvent\x12!\n" +
	"\x04type\x18\x01 \x01(\x0e2\r.v1.EventTypeR\x04type\x12\x16\n" +
	"\x06txHash\x18\x02 \x01(\tR\x06txHash\";\n" +
	"\x14SubscribePoolRequest\x12#\n" +
	"\x05types\x18\x01 \x03(\x0e2\r.v1.EventTypeR\x05types\"%\n" +
	"\tEventData\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayload\"G\n" +
	"\x1dGossipRegisterContractRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\":\n" +
	"\x1eGossipRegisterContractResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*\x90\x01\n" +
	"\tEventType\x12\t\n" +
	"\x05ADDED\x10\x00\x12\f\n" +
	"\bENQUEUED\x10\x01\x12\f\n" +
	"\bPROMOTED\x10\x02\x12\v\n" +
	"\aDROPPED\x10\x03\x12\v\n" +
	"\aDEMOTED\x10\x04\x12\x13\n" +
	"\x0fPRUNED_PROMOTED\x10\x05\x12\x13\n" +
	"\x0fPRUNED_ENQUEUED\x10\x06\x12\x18\n" +
	"\x14SUBGRAPH_EVENT_ADDED\x10\a2\xf5\x02\n" +
	"\x0fTxnPoolOperator\x12O\n" +
	"\x06Status\x12\x16.google.protobuf.Empty\x1a\x15.v1.TxnPoolStatusResp\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/txpool/status\x12?\n" +
	"\x06AddTxn\x12\r.v1.AddTxnReq\x1a\x0e.v1.AddTxnResp\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/txpool/add\x12\x7f\n" +
	"\x10RegisterContract\x12!.v1.GossipRegisterContractRequest\x1a\".v1.GossipRegisterContractResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/txpool/contract/register\x12O\n" +
	"\tSubscribe\x12\x14.v1.SubscribeRequest\x1a\x0f.v1.TxPoolEvent\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/txpool/subscribe0\x01B\x0fZ\r/txpool/protob\x06proto3"

var (
	file_txpool_proto_operator_proto_rawDescOnce sync.Once
	file_txpool_proto_operator_proto_rawDescData []byte
)

func file_txpool_proto_operator_proto_rawDescGZIP() []byte {
	file_txpool_proto_operator_proto_rawDescOnce.Do(func() {
		file_txpool_proto_operator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_txpool_proto_operator_proto_rawDesc), len(file_txpool_proto_operator_proto_rawDesc)))
	})
	return file_txpool_proto_operator_proto_rawDescData
}

var file_txpool_proto_operator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_txpool_proto_operator_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_txpool_proto_operator_proto_goTypes = []any{
	(EventType)(0),                         // 0: v1.EventType
	(*AddTxnReq)(nil),                      // 1: v1.AddTxnReq
	(*AddTxnResp)(nil),                     // 2: v1.AddTxnResp
	(*TxnPoolStatusResp)(nil),              // 3: v1.TxnPoolStatusResp
	(*SubscribeRequest)(nil),               // 4: v1.SubscribeRequest
	(*TxPoolEvent)(nil),                    // 5: v1.TxPoolEvent
	(*SubscribePoolRequest)(nil),           // 6: v1.SubscribePoolRequest
	(*EventData)(nil),                      // 7: v1.EventData
	(*GossipRegisterContractRequest)(nil),  // 8: v1.GossipRegisterContractRequest
	(*GossipRegisterContractResponse)(nil), // 9: v1.GossipRegisterContractResponse
	(*emptypb.Empty)(nil),                  // 10: google.protobuf.Empty
}
var file_txpool_proto_operator_proto_depIdxs = []int32{
	0,  // 0: v1.SubscribeRequest.types:type_name -> v1.EventType
	0,  // 1: v1.TxPoolEvent.type:type_name -> v1.EventType
	0,  // 2: v1.SubscribePoolRequest.types:type_name -> v1.EventType
	10, // 3: v1.TxnPoolOperator.Status:input_type -> google.protobuf.Empty
	1,  // 4: v1.TxnPoolOperator.AddTxn:input_type -> v1.AddTxnReq
	8,  // 5: v1.TxnPoolOperator.RegisterContract:input_type -> v1.GossipRegisterContractRequest
	4,  // 6: v1.TxnPoolOperator.Subscribe:input_type -> v1.SubscribeRequest
	3,  // 7: v1.TxnPoolOperator.Status:output_type -> v1.TxnPoolStatusResp
	2,  // 8: v1.TxnPoolOperator.AddTxn:output_type -> v1.AddTxnResp
	9,  // 9: v1.TxnPoolOperator.RegisterContract:output_type -> v1.GossipRegisterContractResponse
	5,  // 10: v1.TxnPoolOperator.Subscribe:output_type -> v1.TxPoolEvent
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_txpool_proto_operator_proto_init() }
func file_txpool_proto_operator_proto_init() {
	if File_txpool_proto_operator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_txpool_proto_operator_proto_rawDesc), len(file_txpool_proto_operator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_txpool_proto_operator_proto_goTypes,
		DependencyIndexes: file_txpool_proto_operator_proto_depIdxs,
		EnumInfos:         file_txpool_proto_operator_proto_enumTypes,
		MessageInfos:      file_txpool_proto_operator_proto_msgTypes,
	}.Build()
	File_txpool_proto_operator_proto = out.File
	file_txpool_proto_operator_proto_goTypes = nil
	file_txpool_proto_operator_proto_depIdxs = nil
}
