// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: txpool/proto/v1.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Txn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           *anypb.Any             `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Txn) Reset() {
	*x = Txn{}
	mi := &file_txpool_proto_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Txn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Txn) ProtoMessage() {}

func (x *Txn) ProtoReflect() protoreflect.Message {
	mi := &file_txpool_proto_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Txn.ProtoReflect.Descriptor instead.
func (*Txn) Descriptor() ([]byte, []int) {
	return file_txpool_proto_v1_proto_rawDescGZIP(), []int{0}
}

func (x *Txn) GetRaw() *anypb.Any {
	if x != nil {
		return x.Raw
	}
	return nil
}

type RegisterContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           *anypb.Any             `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterContractRequest) Reset() {
	*x = RegisterContractRequest{}
	mi := &file_txpool_proto_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterContractRequest) ProtoMessage() {}

func (x *RegisterContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_txpool_proto_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterContractRequest.ProtoReflect.Descriptor instead.
func (*RegisterContractRequest) Descriptor() ([]byte, []int) {
	return file_txpool_proto_v1_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterContractRequest) GetRaw() *anypb.Any {
	if x != nil {
		return x.Raw
	}
	return nil
}

var File_txpool_proto_v1_proto protoreflect.FileDescriptor

const file_txpool_proto_v1_proto_rawDesc = "" +
	"\n" +
	"\x15txpool/proto/v1.proto\x12\x02v1\x1a\x19google/protobuf/any.proto\"-\n" +
	"\x03Txn\x12&\n" +
	"\x03raw\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x03raw\"A\n" +
	"\x17RegisterContractRequest\x12&\n" +
	"\x03raw\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x03rawB\x0fZ\r/txpool/protob\x06proto3"

var (
	file_txpool_proto_v1_proto_rawDescOnce sync.Once
	file_txpool_proto_v1_proto_rawDescData []byte
)

func file_txpool_proto_v1_proto_rawDescGZIP() []byte {
	file_txpool_proto_v1_proto_rawDescOnce.Do(func() {
		file_txpool_proto_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_txpool_proto_v1_proto_rawDesc), len(file_txpool_proto_v1_proto_rawDesc)))
	})
	return file_txpool_proto_v1_proto_rawDescData
}

var file_txpool_proto_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_txpool_proto_v1_proto_goTypes = []any{
	(*Txn)(nil),                     // 0: v1.Txn
	(*RegisterContractRequest)(nil), // 1: v1.RegisterContractRequest
	(*anypb.Any)(nil),               // 2: google.protobuf.Any
}
var file_txpool_proto_v1_proto_depIdxs = []int32{
	2, // 0: v1.Txn.raw:type_name -> google.protobuf.Any
	2, // 1: v1.RegisterContractRequest.raw:type_name -> google.protobuf.Any
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_txpool_proto_v1_proto_init() }
func file_txpool_proto_v1_proto_init() {
	if File_txpool_proto_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_txpool_proto_v1_proto_rawDesc), len(file_txpool_proto_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_txpool_proto_v1_proto_goTypes,
		DependencyIndexes: file_txpool_proto_v1_proto_depIdxs,
		MessageInfos:      file_txpool_proto_v1_proto_msgTypes,
	}.Build()
	File_txpool_proto_v1_proto = out.File
	file_txpool_proto_v1_proto_goTypes = nil
	file_txpool_proto_v1_proto_depIdxs = nil
}
