// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: consensus/ibft/proto/ibft_operator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IbftStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IbftStatusResp) Reset() {
	*x = IbftStatusResp{}
	mi := &file_consensus_ibft_proto_ibft_operator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IbftStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IbftStatusResp) ProtoMessage() {}

func (x *IbftStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_ibft_proto_ibft_operator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IbftStatusResp.ProtoReflect.Descriptor instead.
func (*IbftStatusResp) Descriptor() ([]byte, []int) {
	return file_consensus_ibft_proto_ibft_operator_proto_rawDescGZIP(), []int{0}
}

func (x *IbftStatusResp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SnapshotReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latest        bool                   `protobuf:"varint,1,opt,name=latest,proto3" json:"latest,omitempty"`
	Number        uint64                 `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotReq) Reset() {
	*x = SnapshotReq{}
	mi := &file_consensus_ibft_proto_ibft_operator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotReq) ProtoMessage() {}

func (x *SnapshotReq) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_ibft_proto_ibft_operator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotReq.ProtoReflect.Descriptor instead.
func (*SnapshotReq) Descriptor() ([]byte, []int) {
	return file_consensus_ibft_proto_ibft_operator_proto_rawDescGZIP(), []int{1}
}

func (x *SnapshotReq) GetLatest() bool {
	if x != nil {
		return x.Latest
	}
	return false
}

func (x *SnapshotReq) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Validators    []*Snapshot_Validator  `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
	Number        uint64                 `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Votes         []*Snapshot_Vote       `protobuf:"bytes,4,rep,name=votes,proto3" json:"votes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_consensus_ibft_proto_ibft_operator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_ibft_proto_ibft_operator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_consensus_ibft_proto_ibft_operator_proto_rawDescGZIP(), []int{2}
}

func (x *Snapshot) GetValidators() []*Snapshot_Validator {
	if x != nil {
		return x.Validators
	}
	return nil
}

func (x *Snapshot) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Snapshot) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Snapshot) GetVotes() []*Snapshot_Vote {
	if x != nil {
		return x.Votes
	}
	return nil
}

type ProposeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Auth          bool                   `protobuf:"varint,2,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeReq) Reset() {
	*x = ProposeReq{}
	mi := &file_consensus_ibft_proto_ibft_operator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeReq) ProtoMessage() {}

func (x *ProposeReq) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_ibft_proto_ibft_operator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeReq.ProtoReflect.Descriptor instead.
func (*ProposeReq) Descriptor() ([]byte, []int) {
	return file_consensus_ibft_proto_ibft_operator_proto_rawDescGZIP(), []int{3}
}

func (x *ProposeReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ProposeReq) GetAuth() bool {
	if x != nil {
		return x.Auth
	}
	return false
}

type CandidatesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidates    []*Candidate           `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandidatesResp) Reset() {
	*x = CandidatesResp{}
	mi := &file_consensus_ibft_proto_ibft_operator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidatesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidatesResp) ProtoMessage() {}

func (x *CandidatesResp) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_ibft_proto_ibft_operator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidatesResp.ProtoReflect.Descriptor instead.
func (*CandidatesResp) Descriptor() ([]byte, []int) {
	return file_consensus_ibft_proto_ibft_operator_proto_rawDescGZIP(), []int{4}
}

func (x *CandidatesResp) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type Candidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	BlsPubkey     []byte                 `protobuf:"bytes,2,opt,name=bls_pubkey,json=blsPubkey,proto3" json:"bls_pubkey,omitempty"`
	Auth          bool                   `protobuf:"varint,3,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	mi := &file_consensus_ibft_proto_ibft_operator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_ibft_proto_ibft_operator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_consensus_ibft_proto_ibft_operator_proto_rawDescGZIP(), []int{5}
}

func (x *Candidate) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Candidate) GetBlsPubkey() []byte {
	if x != nil {
		return x.BlsPubkey
	}
	return nil
}

func (x *Candidate) GetAuth() bool {
	if x != nil {
		return x.Auth
	}
	return false
}

type Snapshot_Validator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot_Validator) Reset() {
	*x = Snapshot_Validator{}
	mi := &file_consensus_ibft_proto_ibft_operator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot_Validator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot_Validator) ProtoMessage() {}

func (x *Snapshot_Validator) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_ibft_proto_ibft_operator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot_Validator.ProtoReflect.Descriptor instead.
func (*Snapshot_Validator) Descriptor() ([]byte, []int) {
	return file_consensus_ibft_proto_ibft_operator_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Snapshot_Validator) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Snapshot_Validator) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Snapshot_Validator) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Snapshot_Vote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Validator     string                 `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	Proposed      string                 `protobuf:"bytes,2,opt,name=proposed,proto3" json:"proposed,omitempty"`
	Auth          bool                   `protobuf:"varint,3,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot_Vote) Reset() {
	*x = Snapshot_Vote{}
	mi := &file_consensus_ibft_proto_ibft_operator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot_Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot_Vote) ProtoMessage() {}

func (x *Snapshot_Vote) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_ibft_proto_ibft_operator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot_Vote.ProtoReflect.Descriptor instead.
func (*Snapshot_Vote) Descriptor() ([]byte, []int) {
	return file_consensus_ibft_proto_ibft_operator_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Snapshot_Vote) GetValidator() string {
	if x != nil {
		return x.Validator
	}
	return ""
}

func (x *Snapshot_Vote) GetProposed() string {
	if x != nil {
		return x.Proposed
	}
	return ""
}

func (x *Snapshot_Vote) GetAuth() bool {
	if x != nil {
		return x.Auth
	}
	return false
}

var File_consensus_ibft_proto_ibft_operator_proto protoreflect.FileDescriptor

const file_consensus_ibft_proto_ibft_operator_proto_rawDesc = "" +
	"\n" +
	"(consensus/ibft/proto/ibft_operator.proto\x12\x02v1\x1a\x1bgoogle/protobuf/empty.proto\"\"\n" +
	"\x0eIbftStatusResp\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"=\n" +
	"\vSnapshotReq\x12\x16\n" +
	"\x06latest\x18\x01 \x01(\bR\x06latest\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x04R\x06number\"\xbc\x02\n" +
	"\bSnapshot\x126\n" +
	"\n" +
	"validators\x18\x01 \x03(\v2\x16.v1.Snapshot.ValidatorR\n" +
	"validators\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x04R\x06number\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12'\n" +
	"\x05votes\x18\x04 \x03(\v2\x11.v1.Snapshot.VoteR\x05votes\x1aM\n" +
	"\tValidator\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x1aT\n" +
	"\x04Vote\x12\x1c\n" +
	"\tvalidator\x18\x01 \x01(\tR\tvalidator\x12\x1a\n" +
	"\bproposed\x18\x02 \x01(\tR\bproposed\x12\x12\n" +
	"\x04auth\x18\x03 \x01(\bR\x04auth\":\n" +
	"\n" +
	"ProposeReq\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04auth\x18\x02 \x01(\bR\x04auth\"?\n" +
	"\x0eCandidatesResp\x12-\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2\r.v1.CandidateR\n" +
	"candidates\"X\n" +
	"\tCandidate\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"bls_pubkey\x18\x02 \x01(\fR\tblsPubkey\x12\x12\n" +
	"\x04auth\x18\x03 \x01(\bR\x04auth2\xde\x01\n" +
	"\fIbftOperator\x12,\n" +
	"\vGetSnapshot\x12\x0f.v1.SnapshotReq\x1a\f.v1.Snapshot\x120\n" +
	"\aPropose\x12\r.v1.Candidate\x1a\x16.google.protobuf.Empty\x128\n" +
	"\n" +
	"Candidates\x12\x16.google.protobuf.Empty\x1a\x12.v1.CandidatesResp\x124\n" +
	"\x06Status\x12\x16.google.protobuf.Empty\x1a\x12.v1.IbftStatusRespB\x17Z\x15/consensus/ibft/protob\x06proto3"

var (
	file_consensus_ibft_proto_ibft_operator_proto_rawDescOnce sync.Once
	file_consensus_ibft_proto_ibft_operator_proto_rawDescData []byte
)

func file_consensus_ibft_proto_ibft_operator_proto_rawDescGZIP() []byte {
	file_consensus_ibft_proto_ibft_operator_proto_rawDescOnce.Do(func() {
		file_consensus_ibft_proto_ibft_operator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_consensus_ibft_proto_ibft_operator_proto_rawDesc), len(file_consensus_ibft_proto_ibft_operator_proto_rawDesc)))
	})
	return file_consensus_ibft_proto_ibft_operator_proto_rawDescData
}

var file_consensus_ibft_proto_ibft_operator_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_consensus_ibft_proto_ibft_operator_proto_goTypes = []any{
	(*IbftStatusResp)(nil),     // 0: v1.IbftStatusResp
	(*SnapshotReq)(nil),        // 1: v1.SnapshotReq
	(*Snapshot)(nil),           // 2: v1.Snapshot
	(*ProposeReq)(nil),         // 3: v1.ProposeReq
	(*CandidatesResp)(nil),     // 4: v1.CandidatesResp
	(*Candidate)(nil),          // 5: v1.Candidate
	(*Snapshot_Validator)(nil), // 6: v1.Snapshot.Validator
	(*Snapshot_Vote)(nil),      // 7: v1.Snapshot.Vote
	(*emptypb.Empty)(nil),      // 8: google.protobuf.Empty
}
var file_consensus_ibft_proto_ibft_operator_proto_depIdxs = []int32{
	6, // 0: v1.Snapshot.validators:type_name -> v1.Snapshot.Validator
	7, // 1: v1.Snapshot.votes:type_name -> v1.Snapshot.Vote
	5, // 2: v1.CandidatesResp.candidates:type_name -> v1.Candidate
	1, // 3: v1.IbftOperator.GetSnapshot:input_type -> v1.SnapshotReq
	5, // 4: v1.IbftOperator.Propose:input_type -> v1.Candidate
	8, // 5: v1.IbftOperator.Candidates:input_type -> google.protobuf.Empty
	8, // 6: v1.IbftOperator.Status:input_type -> google.protobuf.Empty
	2, // 7: v1.IbftOperator.GetSnapshot:output_type -> v1.Snapshot
	8, // 8: v1.IbftOperator.Propose:output_type -> google.protobuf.Empty
	4, // 9: v1.IbftOperator.Candidates:output_type -> v1.CandidatesResp
	0, // 10: v1.IbftOperator.Status:output_type -> v1.IbftStatusResp
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_consensus_ibft_proto_ibft_operator_proto_init() }
func file_consensus_ibft_proto_ibft_operator_proto_init() {
	if File_consensus_ibft_proto_ibft_operator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_consensus_ibft_proto_ibft_operator_proto_rawDesc), len(file_consensus_ibft_proto_ibft_operator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_consensus_ibft_proto_ibft_operator_proto_goTypes,
		DependencyIndexes: file_consensus_ibft_proto_ibft_operator_proto_depIdxs,
		MessageInfos:      file_consensus_ibft_proto_ibft_operator_proto_msgTypes,
	}.Build()
	File_consensus_ibft_proto_ibft_operator_proto = out.File
	file_consensus_ibft_proto_ibft_operator_proto_goTypes = nil
	file_consensus_ibft_proto_ibft_operator_proto_depIdxs = nil
}
