// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ibft/messages/proto/messages.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType defines the types of messages
// circulating in the system
type MessageType int32

const (
	MessageType_PREPREPARE   MessageType = 0
	MessageType_PREPARE      MessageType = 1
	MessageType_COMMIT       MessageType = 2
	MessageType_ROUND_CHANGE MessageType = 3
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "PREPREPARE",
		1: "PREPARE",
		2: "COMMIT",
		3: "ROUND_CHANGE",
	}
	MessageType_value = map[string]int32{
		"PREPREPARE":   0,
		"PREPARE":      1,
		"COMMIT":       2,
		"ROUND_CHANGE": 3,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_ibft_messages_proto_messages_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_ibft_messages_proto_messages_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_ibft_messages_proto_messages_proto_rawDescGZIP(), []int{0}
}

// View defines the current status
type View struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// height represents the number of the proposal
	Height uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	// round represents the round number in the specific height
	Round uint64 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	// version represents the version number in the blockchain
	Version       string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *View) Reset() {
	*x = View{}
	mi := &file_ibft_messages_proto_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *View) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*View) ProtoMessage() {}

func (x *View) ProtoReflect() protoreflect.Message {
	mi := &file_ibft_messages_proto_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use View.ProtoReflect.Descriptor instead.
func (*View) Descriptor() ([]byte, []int) {
	return file_ibft_messages_proto_messages_proto_rawDescGZIP(), []int{0}
}

func (x *View) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *View) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *View) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Message defines the base message structure
type IBFTMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// view is the current view for the message
	View *View `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	// from defines who is the message sender
	From []byte `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// the signature of the sender, if any
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	// type defines the message type
	Type MessageType `protobuf:"varint,4,opt,name=type,proto3,enum=v1.MessageType" json:"type,omitempty"`
	// payload is the specific message payload
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*IBFTMessage_PreprepareData
	//	*IBFTMessage_PrepareData
	//	*IBFTMessage_CommitData
	//	*IBFTMessage_RoundChangeData
	Payload       isIBFTMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IBFTMessage) Reset() {
	*x = IBFTMessage{}
	mi := &file_ibft_messages_proto_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IBFTMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IBFTMessage) ProtoMessage() {}

func (x *IBFTMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ibft_messages_proto_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IBFTMessage.ProtoReflect.Descriptor instead.
func (*IBFTMessage) Descriptor() ([]byte, []int) {
	return file_ibft_messages_proto_messages_proto_rawDescGZIP(), []int{1}
}

func (x *IBFTMessage) GetView() *View {
	if x != nil {
		return x.View
	}
	return nil
}

func (x *IBFTMessage) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *IBFTMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *IBFTMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_PREPREPARE
}

func (x *IBFTMessage) GetPayload() isIBFTMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *IBFTMessage) GetPreprepareData() *PrePrepareMessage {
	if x != nil {
		if x, ok := x.Payload.(*IBFTMessage_PreprepareData); ok {
			return x.PreprepareData
		}
	}
	return nil
}

func (x *IBFTMessage) GetPrepareData() *PrepareMessage {
	if x != nil {
		if x, ok := x.Payload.(*IBFTMessage_PrepareData); ok {
			return x.PrepareData
		}
	}
	return nil
}

func (x *IBFTMessage) GetCommitData() *CommitMessage {
	if x != nil {
		if x, ok := x.Payload.(*IBFTMessage_CommitData); ok {
			return x.CommitData
		}
	}
	return nil
}

func (x *IBFTMessage) GetRoundChangeData() *RoundChangeMessage {
	if x != nil {
		if x, ok := x.Payload.(*IBFTMessage_RoundChangeData); ok {
			return x.RoundChangeData
		}
	}
	return nil
}

type isIBFTMessage_Payload interface {
	isIBFTMessage_Payload()
}

type IBFTMessage_PreprepareData struct {
	PreprepareData *PrePrepareMessage `protobuf:"bytes,5,opt,name=preprepareData,proto3,oneof"`
}

type IBFTMessage_PrepareData struct {
	PrepareData *PrepareMessage `protobuf:"bytes,6,opt,name=prepareData,proto3,oneof"`
}

type IBFTMessage_CommitData struct {
	CommitData *CommitMessage `protobuf:"bytes,7,opt,name=commitData,proto3,oneof"`
}

type IBFTMessage_RoundChangeData struct {
	RoundChangeData *RoundChangeMessage `protobuf:"bytes,8,opt,name=roundChangeData,proto3,oneof"`
}

func (*IBFTMessage_PreprepareData) isIBFTMessage_Payload() {}

func (*IBFTMessage_PrepareData) isIBFTMessage_Payload() {}

func (*IBFTMessage_CommitData) isIBFTMessage_Payload() {}

func (*IBFTMessage_RoundChangeData) isIBFTMessage_Payload() {}

// PrePrepareMessage is the message for the PREPREPARE phase
type PrePrepareMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// proposal is the actual data being proposed for consensus
	Proposal []byte `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal,omitempty"`
	// proposalHash is the Keccak hash of the proposal
	ProposalHash []byte `protobuf:"bytes,2,opt,name=proposalHash,proto3" json:"proposalHash,omitempty"`
	// certificate is the RCC that can accompany
	// a proposal message
	Certificate   *RoundChangeCertificate `protobuf:"bytes,3,opt,name=certificate,proto3" json:"certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrePrepareMessage) Reset() {
	*x = PrePrepareMessage{}
	mi := &file_ibft_messages_proto_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrePrepareMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrePrepareMessage) ProtoMessage() {}

func (x *PrePrepareMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ibft_messages_proto_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrePrepareMessage.ProtoReflect.Descriptor instead.
func (*PrePrepareMessage) Descriptor() ([]byte, []int) {
	return file_ibft_messages_proto_messages_proto_rawDescGZIP(), []int{2}
}

func (x *PrePrepareMessage) GetProposal() []byte {
	if x != nil {
		return x.Proposal
	}
	return nil
}

func (x *PrePrepareMessage) GetProposalHash() []byte {
	if x != nil {
		return x.ProposalHash
	}
	return nil
}

func (x *PrePrepareMessage) GetCertificate() *RoundChangeCertificate {
	if x != nil {
		return x.Certificate
	}
	return nil
}

// PrepareMessage is the message for the PREPARE phase
type PrepareMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// proposalHash is the Keccak hash of the proposal
	ProposalHash  []byte `protobuf:"bytes,1,opt,name=proposalHash,proto3" json:"proposalHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareMessage) Reset() {
	*x = PrepareMessage{}
	mi := &file_ibft_messages_proto_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareMessage) ProtoMessage() {}

func (x *PrepareMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ibft_messages_proto_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareMessage.ProtoReflect.Descriptor instead.
func (*PrepareMessage) Descriptor() ([]byte, []int) {
	return file_ibft_messages_proto_messages_proto_rawDescGZIP(), []int{3}
}

func (x *PrepareMessage) GetProposalHash() []byte {
	if x != nil {
		return x.ProposalHash
	}
	return nil
}

// CommitMessage is the message for the COMMIT phase
type CommitMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// proposalHash is the Keccak hash of the proposal
	ProposalHash []byte `protobuf:"bytes,1,opt,name=proposalHash,proto3" json:"proposalHash,omitempty"`
	// committedSeal is the seal of the sender
	CommittedSeal []byte `protobuf:"bytes,2,opt,name=committedSeal,proto3" json:"committedSeal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitMessage) Reset() {
	*x = CommitMessage{}
	mi := &file_ibft_messages_proto_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitMessage) ProtoMessage() {}

func (x *CommitMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ibft_messages_proto_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitMessage.ProtoReflect.Descriptor instead.
func (*CommitMessage) Descriptor() ([]byte, []int) {
	return file_ibft_messages_proto_messages_proto_rawDescGZIP(), []int{4}
}

func (x *CommitMessage) GetProposalHash() []byte {
	if x != nil {
		return x.ProposalHash
	}
	return nil
}

func (x *CommitMessage) GetCommittedSeal() []byte {
	if x != nil {
		return x.CommittedSeal
	}
	return nil
}

// RoundChangeMessage is the message for the ROUND CHANGE phase
type RoundChangeMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// lastPreparedProposedBlock is the last block
	// to reach Q(N) - 1 PREPARE messages
	LastPreparedProposedBlock []byte `protobuf:"bytes,1,opt,name=lastPreparedProposedBlock,proto3" json:"lastPreparedProposedBlock,omitempty"`
	// latestPreparedCertificate is the PC that accompanies
	// the last proposal
	LatestPreparedCertificate *PreparedCertificate `protobuf:"bytes,2,opt,name=latestPreparedCertificate,proto3" json:"latestPreparedCertificate,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *RoundChangeMessage) Reset() {
	*x = RoundChangeMessage{}
	mi := &file_ibft_messages_proto_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundChangeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundChangeMessage) ProtoMessage() {}

func (x *RoundChangeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ibft_messages_proto_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundChangeMessage.ProtoReflect.Descriptor instead.
func (*RoundChangeMessage) Descriptor() ([]byte, []int) {
	return file_ibft_messages_proto_messages_proto_rawDescGZIP(), []int{5}
}

func (x *RoundChangeMessage) GetLastPreparedProposedBlock() []byte {
	if x != nil {
		return x.LastPreparedProposedBlock
	}
	return nil
}

func (x *RoundChangeMessage) GetLatestPreparedCertificate() *PreparedCertificate {
	if x != nil {
		return x.LatestPreparedCertificate
	}
	return nil
}

// PreparedCertificate is a collection of
// prepare messages for a certain proposal
type PreparedCertificate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// proposalMessage is the proposal message to reach
	// at least Q(N) - 1 PREPARE messages
	ProposalMessage *IBFTMessage `protobuf:"bytes,1,opt,name=proposalMessage,proto3" json:"proposalMessage,omitempty"`
	// prepareMessages are the PREPARE messages at least Q(N) - 1
	PrepareMessages []*IBFTMessage `protobuf:"bytes,2,rep,name=prepareMessages,proto3" json:"prepareMessages,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PreparedCertificate) Reset() {
	*x = PreparedCertificate{}
	mi := &file_ibft_messages_proto_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreparedCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreparedCertificate) ProtoMessage() {}

func (x *PreparedCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_ibft_messages_proto_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreparedCertificate.ProtoReflect.Descriptor instead.
func (*PreparedCertificate) Descriptor() ([]byte, []int) {
	return file_ibft_messages_proto_messages_proto_rawDescGZIP(), []int{6}
}

func (x *PreparedCertificate) GetProposalMessage() *IBFTMessage {
	if x != nil {
		return x.ProposalMessage
	}
	return nil
}

func (x *PreparedCertificate) GetPrepareMessages() []*IBFTMessage {
	if x != nil {
		return x.PrepareMessages
	}
	return nil
}

// RoundChangeCertificate is a collection of
// round change messages for a certain round
type RoundChangeCertificate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// roundChangeMessages are the ROUND CHANGE messages
	RoundChangeMessages []*IBFTMessage `protobuf:"bytes,1,rep,name=roundChangeMessages,proto3" json:"roundChangeMessages,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RoundChangeCertificate) Reset() {
	*x = RoundChangeCertificate{}
	mi := &file_ibft_messages_proto_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundChangeCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundChangeCertificate) ProtoMessage() {}

func (x *RoundChangeCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_ibft_messages_proto_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundChangeCertificate.ProtoReflect.Descriptor instead.
func (*RoundChangeCertificate) Descriptor() ([]byte, []int) {
	return file_ibft_messages_proto_messages_proto_rawDescGZIP(), []int{7}
}

func (x *RoundChangeCertificate) GetRoundChangeMessages() []*IBFTMessage {
	if x != nil {
		return x.RoundChangeMessages
	}
	return nil
}

var File_ibft_messages_proto_messages_proto protoreflect.FileDescriptor

const file_ibft_messages_proto_messages_proto_rawDesc = "" +
	"\n" +
	"\"ibft/messages/proto/messages.proto\x12\x02v1\"N\n" +
	"\x04View\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x04R\x05round\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\xff\x02\n" +
	"\vIBFTMessage\x12\x1c\n" +
	"\x04view\x18\x01 \x01(\v2\b.v1.ViewR\x04view\x12\x12\n" +
	"\x04from\x18\x02 \x01(\fR\x04from\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12#\n" +
	"\x04type\x18\x04 \x01(\x0e2\x0f.v1.MessageTypeR\x04type\x12?\n" +
	"\x0epreprepareData\x18\x05 \x01(\v2\x15.v1.PrePrepareMessageH\x00R\x0epreprepareData\x126\n" +
	"\vprepareData\x18\x06 \x01(\v2\x12.v1.PrepareMessageH\x00R\vprepareData\x123\n" +
	"\n" +
	"commitData\x18\a \x01(\v2\x11.v1.CommitMessageH\x00R\n" +
	"commitData\x12B\n" +
	"\x0froundChangeData\x18\b \x01(\v2\x16.v1.RoundChangeMessageH\x00R\x0froundChangeDataB\t\n" +
	"\apayload\"\x91\x01\n" +
	"\x11PrePrepareMessage\x12\x1a\n" +
	"\bproposal\x18\x01 \x01(\fR\bproposal\x12\"\n" +
	"\fproposalHash\x18\x02 \x01(\fR\fproposalHash\x12<\n" +
	"\vcertificate\x18\x03 \x01(\v2\x1a.v1.RoundChangeCertificateR\vcertificate\"4\n" +
	"\x0ePrepareMessage\x12\"\n" +
	"\fproposalHash\x18\x01 \x01(\fR\fproposalHash\"Y\n" +
	"\rCommitMessage\x12\"\n" +
	"\fproposalHash\x18\x01 \x01(\fR\fproposalHash\x12$\n" +
	"\rcommittedSeal\x18\x02 \x01(\fR\rcommittedSeal\"\xa9\x01\n" +
	"\x12RoundChangeMessage\x12<\n" +
	"\x19lastPreparedProposedBlock\x18\x01 \x01(\fR\x19lastPreparedProposedBlock\x12U\n" +
	"\x19latestPreparedCertificate\x18\x02 \x01(\v2\x17.v1.PreparedCertificateR\x19latestPreparedCertificate\"\x8b\x01\n" +
	"\x13PreparedCertificate\x129\n" +
	"\x0fproposalMessage\x18\x01 \x01(\v2\x0f.v1.IBFTMessageR\x0fproposalMessage\x129\n" +
	"\x0fprepareMessages\x18\x02 \x03(\v2\x0f.v1.IBFTMessageR\x0fprepareMessages\"[\n" +
	"\x16RoundChangeCertificate\x12A\n" +
	"\x13roundChangeMessages\x18\x01 \x03(\v2\x0f.v1.IBFTMessageR\x13roundChangeMessages*H\n" +
	"\vMessageType\x12\x0e\n" +
	"\n" +
	"PREPREPARE\x10\x00\x12\v\n" +
	"\aPREPARE\x10\x01\x12\n" +
	"\n" +
	"\x06COMMIT\x10\x02\x12\x10\n" +
	"\fROUND_CHANGE\x10\x03B\x11Z\x0f/messages/protob\x06proto3"

var (
	file_ibft_messages_proto_messages_proto_rawDescOnce sync.Once
	file_ibft_messages_proto_messages_proto_rawDescData []byte
)

func file_ibft_messages_proto_messages_proto_rawDescGZIP() []byte {
	file_ibft_messages_proto_messages_proto_rawDescOnce.Do(func() {
		file_ibft_messages_proto_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ibft_messages_proto_messages_proto_rawDesc), len(file_ibft_messages_proto_messages_proto_rawDesc)))
	})
	return file_ibft_messages_proto_messages_proto_rawDescData
}

var file_ibft_messages_proto_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ibft_messages_proto_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ibft_messages_proto_messages_proto_goTypes = []any{
	(MessageType)(0),               // 0: v1.MessageType
	(*View)(nil),                   // 1: v1.View
	(*IBFTMessage)(nil),            // 2: v1.IBFTMessage
	(*PrePrepareMessage)(nil),      // 3: v1.PrePrepareMessage
	(*PrepareMessage)(nil),         // 4: v1.PrepareMessage
	(*CommitMessage)(nil),          // 5: v1.CommitMessage
	(*RoundChangeMessage)(nil),     // 6: v1.RoundChangeMessage
	(*PreparedCertificate)(nil),    // 7: v1.PreparedCertificate
	(*RoundChangeCertificate)(nil), // 8: v1.RoundChangeCertificate
}
var file_ibft_messages_proto_messages_proto_depIdxs = []int32{
	1,  // 0: v1.IBFTMessage.view:type_name -> v1.View
	0,  // 1: v1.IBFTMessage.type:type_name -> v1.MessageType
	3,  // 2: v1.IBFTMessage.preprepareData:type_name -> v1.PrePrepareMessage
	4,  // 3: v1.IBFTMessage.prepareData:type_name -> v1.PrepareMessage
	5,  // 4: v1.IBFTMessage.commitData:type_name -> v1.CommitMessage
	6,  // 5: v1.IBFTMessage.roundChangeData:type_name -> v1.RoundChangeMessage
	8,  // 6: v1.PrePrepareMessage.certificate:type_name -> v1.RoundChangeCertificate
	7,  // 7: v1.RoundChangeMessage.latestPreparedCertificate:type_name -> v1.PreparedCertificate
	2,  // 8: v1.PreparedCertificate.proposalMessage:type_name -> v1.IBFTMessage
	2,  // 9: v1.PreparedCertificate.prepareMessages:type_name -> v1.IBFTMessage
	2,  // 10: v1.RoundChangeCertificate.roundChangeMessages:type_name -> v1.IBFTMessage
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_ibft_messages_proto_messages_proto_init() }
func file_ibft_messages_proto_messages_proto_init() {
	if File_ibft_messages_proto_messages_proto != nil {
		return
	}
	file_ibft_messages_proto_messages_proto_msgTypes[1].OneofWrappers = []any{
		(*IBFTMessage_PreprepareData)(nil),
		(*IBFTMessage_PrepareData)(nil),
		(*IBFTMessage_CommitData)(nil),
		(*IBFTMessage_RoundChangeData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ibft_messages_proto_messages_proto_rawDesc), len(file_ibft_messages_proto_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ibft_messages_proto_messages_proto_goTypes,
		DependencyIndexes: file_ibft_messages_proto_messages_proto_depIdxs,
		EnumInfos:         file_ibft_messages_proto_messages_proto_enumTypes,
		MessageInfos:      file_ibft_messages_proto_messages_proto_msgTypes,
	}.Build()
	File_ibft_messages_proto_messages_proto = out.File
	file_ibft_messages_proto_messages_proto_goTypes = nil
	file_ibft_messages_proto_messages_proto_depIdxs = nil
}
