// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: network/proto/discovery.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindPeersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindPeersReq) Reset() {
	*x = FindPeersReq{}
	mi := &file_network_proto_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindPeersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindPeersReq) ProtoMessage() {}

func (x *FindPeersReq) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindPeersReq.ProtoReflect.Descriptor instead.
func (*FindPeersReq) Descriptor() ([]byte, []int) {
	return file_network_proto_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *FindPeersReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FindPeersReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type FindPeersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []string               `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindPeersResp) Reset() {
	*x = FindPeersResp{}
	mi := &file_network_proto_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindPeersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindPeersResp) ProtoMessage() {}

func (x *FindPeersResp) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindPeersResp.ProtoReflect.Descriptor instead.
func (*FindPeersResp) Descriptor() ([]byte, []int) {
	return file_network_proto_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *FindPeersResp) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_network_proto_discovery_proto protoreflect.FileDescriptor

const file_network_proto_discovery_proto_rawDesc = "" +
	"\n" +
	"\x1dnetwork/proto/discovery.proto\x12\x02v1\"6\n" +
	"\fFindPeersReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"%\n" +
	"\rFindPeersResp\x12\x14\n" +
	"\x05nodes\x18\x01 \x03(\tR\x05nodes2=\n" +
	"\tDiscovery\x120\n" +
	"\tFindPeers\x12\x10.v1.FindPeersReq\x1a\x11.v1.FindPeersRespB\x10Z\x0e/network/protob\x06proto3"

var (
	file_network_proto_discovery_proto_rawDescOnce sync.Once
	file_network_proto_discovery_proto_rawDescData []byte
)

func file_network_proto_discovery_proto_rawDescGZIP() []byte {
	file_network_proto_discovery_proto_rawDescOnce.Do(func() {
		file_network_proto_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_proto_discovery_proto_rawDesc), len(file_network_proto_discovery_proto_rawDesc)))
	})
	return file_network_proto_discovery_proto_rawDescData
}

var file_network_proto_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_network_proto_discovery_proto_goTypes = []any{
	(*FindPeersReq)(nil),  // 0: v1.FindPeersReq
	(*FindPeersResp)(nil), // 1: v1.FindPeersResp
}
var file_network_proto_discovery_proto_depIdxs = []int32{
	0, // 0: v1.Discovery.FindPeers:input_type -> v1.FindPeersReq
	1, // 1: v1.Discovery.FindPeers:output_type -> v1.FindPeersResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_network_proto_discovery_proto_init() }
func file_network_proto_discovery_proto_init() {
	if File_network_proto_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_proto_discovery_proto_rawDesc), len(file_network_proto_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_network_proto_discovery_proto_goTypes,
		DependencyIndexes: file_network_proto_discovery_proto_depIdxs,
		MessageInfos:      file_network_proto_discovery_proto_msgTypes,
	}.Build()
	File_network_proto_discovery_proto = out.File
	file_network_proto_discovery_proto_goTypes = nil
	file_network_proto_discovery_proto_depIdxs = nil
}
