// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: network/proto/identity.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      map[string]string      `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Keys          []*Status_Key          `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	Chain         int64                  `protobuf:"varint,3,opt,name=chain,proto3" json:"chain,omitempty"`
	Genesis       string                 `protobuf:"bytes,4,opt,name=genesis,proto3" json:"genesis,omitempty"`
	TemporaryDial bool                   `protobuf:"varint,5,opt,name=temporaryDial,proto3" json:"temporaryDial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_network_proto_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_network_proto_identity_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Status) GetKeys() []*Status_Key {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *Status) GetChain() int64 {
	if x != nil {
		return x.Chain
	}
	return 0
}

func (x *Status) GetGenesis() string {
	if x != nil {
		return x.Genesis
	}
	return ""
}

func (x *Status) GetTemporaryDial() bool {
	if x != nil {
		return x.TemporaryDial
	}
	return false
}

type Status_Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     string                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status_Key) Reset() {
	*x = Status_Key{}
	mi := &file_network_proto_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status_Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status_Key) ProtoMessage() {}

func (x *Status_Key) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status_Key.ProtoReflect.Descriptor instead.
func (*Status_Key) Descriptor() ([]byte, []int) {
	return file_network_proto_identity_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Status_Key) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Status_Key) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_network_proto_identity_proto protoreflect.FileDescriptor

const file_network_proto_identity_proto_rawDesc = "" +
	"\n" +
	"\x1cnetwork/proto/identity.proto\x12\x02v1\"\xb4\x02\n" +
	"\x06Status\x124\n" +
	"\bmetadata\x18\x01 \x03(\v2\x18.v1.Status.MetadataEntryR\bmetadata\x12\"\n" +
	"\x04keys\x18\x02 \x03(\v2\x0e.v1.Status.KeyR\x04keys\x12\x14\n" +
	"\x05chain\x18\x03 \x01(\x03R\x05chain\x12\x18\n" +
	"\agenesis\x18\x04 \x01(\tR\agenesis\x12$\n" +
	"\rtemporaryDial\x18\x05 \x01(\bR\rtemporaryDial\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x03Key\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2+\n" +
	"\bIdentity\x12\x1f\n" +
	"\x05Hello\x12\n" +
	".v1.Status\x1a\n" +
	".v1.StatusB\x10Z\x0e/network/protob\x06proto3"

var (
	file_network_proto_identity_proto_rawDescOnce sync.Once
	file_network_proto_identity_proto_rawDescData []byte
)

func file_network_proto_identity_proto_rawDescGZIP() []byte {
	file_network_proto_identity_proto_rawDescOnce.Do(func() {
		file_network_proto_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_proto_identity_proto_rawDesc), len(file_network_proto_identity_proto_rawDesc)))
	})
	return file_network_proto_identity_proto_rawDescData
}

var file_network_proto_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_network_proto_identity_proto_goTypes = []any{
	(*Status)(nil),     // 0: v1.Status
	nil,                // 1: v1.Status.MetadataEntry
	(*Status_Key)(nil), // 2: v1.Status.Key
}
var file_network_proto_identity_proto_depIdxs = []int32{
	1, // 0: v1.Status.metadata:type_name -> v1.Status.MetadataEntry
	2, // 1: v1.Status.keys:type_name -> v1.Status.Key
	0, // 2: v1.Identity.Hello:input_type -> v1.Status
	0, // 3: v1.Identity.Hello:output_type -> v1.Status
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_network_proto_identity_proto_init() }
func file_network_proto_identity_proto_init() {
	if File_network_proto_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_proto_identity_proto_rawDesc), len(file_network_proto_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_network_proto_identity_proto_goTypes,
		DependencyIndexes: file_network_proto_identity_proto_depIdxs,
		MessageInfos:      file_network_proto_identity_proto_msgTypes,
	}.Build()
	File_network_proto_identity_proto = out.File
	file_network_proto_identity_proto_goTypes = nil
	file_network_proto_identity_proto_depIdxs = nil
}
