// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: network/proto/testing.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenericMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericMessage) Reset() {
	*x = GenericMessage{}
	mi := &file_network_proto_testing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericMessage) ProtoMessage() {}

func (x *GenericMessage) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_testing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericMessage.ProtoReflect.Descriptor instead.
func (*GenericMessage) Descriptor() ([]byte, []int) {
	return file_network_proto_testing_proto_rawDescGZIP(), []int{0}
}

func (x *GenericMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ChattyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChattyRequest) Reset() {
	*x = ChattyRequest{}
	mi := &file_network_proto_testing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChattyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChattyRequest) ProtoMessage() {}

func (x *ChattyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_testing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChattyRequest.ProtoReflect.Descriptor instead.
func (*ChattyRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_testing_proto_rawDescGZIP(), []int{1}
}

func (x *ChattyRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChattyRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_network_proto_testing_proto protoreflect.FileDescriptor

const file_network_proto_testing_proto_rawDesc = "" +
	"\n" +
	"\x1bnetwork/proto/testing.proto\x12\x02v1\"*\n" +
	"\x0eGenericMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"?\n" +
	"\rChattyRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count2\xf7\x01\n" +
	"\vTestService\x122\n" +
	"\bSayHello\x12\x12.v1.GenericMessage\x1a\x12.v1.GenericMessage\x12:\n" +
	"\x0fGetChattyServer\x12\x11.v1.ChattyRequest\x1a\x12.v1.GenericMessage0\x01\x12;\n" +
	"\x0fGetChattyClient\x12\x12.v1.GenericMessage\x1a\x12.v1.GenericMessage(\x01\x12;\n" +
	"\rGetChattyBidi\x12\x12.v1.GenericMessage\x1a\x12.v1.GenericMessage(\x010\x01B\x10Z\x0e/network/protob\x06proto3"

var (
	file_network_proto_testing_proto_rawDescOnce sync.Once
	file_network_proto_testing_proto_rawDescData []byte
)

func file_network_proto_testing_proto_rawDescGZIP() []byte {
	file_network_proto_testing_proto_rawDescOnce.Do(func() {
		file_network_proto_testing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_proto_testing_proto_rawDesc), len(file_network_proto_testing_proto_rawDesc)))
	})
	return file_network_proto_testing_proto_rawDescData
}

var file_network_proto_testing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_network_proto_testing_proto_goTypes = []any{
	(*GenericMessage)(nil), // 0: v1.GenericMessage
	(*ChattyRequest)(nil),  // 1: v1.ChattyRequest
}
var file_network_proto_testing_proto_depIdxs = []int32{
	0, // 0: v1.TestService.SayHello:input_type -> v1.GenericMessage
	1, // 1: v1.TestService.GetChattyServer:input_type -> v1.ChattyRequest
	0, // 2: v1.TestService.GetChattyClient:input_type -> v1.GenericMessage
	0, // 3: v1.TestService.GetChattyBidi:input_type -> v1.GenericMessage
	0, // 4: v1.TestService.SayHello:output_type -> v1.GenericMessage
	0, // 5: v1.TestService.GetChattyServer:output_type -> v1.GenericMessage
	0, // 6: v1.TestService.GetChattyClient:output_type -> v1.GenericMessage
	0, // 7: v1.TestService.GetChattyBidi:output_type -> v1.GenericMessage
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_network_proto_testing_proto_init() }
func file_network_proto_testing_proto_init() {
	if File_network_proto_testing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_proto_testing_proto_rawDesc), len(file_network_proto_testing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_network_proto_testing_proto_goTypes,
		DependencyIndexes: file_network_proto_testing_proto_depIdxs,
		MessageInfos:      file_network_proto_testing_proto_msgTypes,
	}.Build()
	File_network_proto_testing_proto = out.File
	file_network_proto_testing_proto_goTypes = nil
	file_network_proto_testing_proto_depIdxs = nil
}
