// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: server/proto/system.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	P2PAddr       string                 `protobuf:"bytes,1,opt,name=p2pAddr,proto3" json:"p2pAddr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatus) Reset() {
	*x = ServerStatus{}
	mi := &file_server_proto_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatus) ProtoMessage() {}

func (x *ServerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatus.ProtoReflect.Descriptor instead.
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return file_server_proto_system_proto_rawDescGZIP(), []int{0}
}

func (x *ServerStatus) GetP2PAddr() string {
	if x != nil {
		return x.P2PAddr
	}
	return ""
}

type Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Protocols     []string               `protobuf:"bytes,2,rep,name=protocols,proto3" json:"protocols,omitempty"`
	Addrs         []string               `protobuf:"bytes,3,rep,name=addrs,proto3" json:"addrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_server_proto_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_server_proto_system_proto_rawDescGZIP(), []int{1}
}

func (x *Peer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Peer) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *Peer) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

type PeersAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeersAddRequest) Reset() {
	*x = PeersAddRequest{}
	mi := &file_server_proto_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeersAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeersAddRequest) ProtoMessage() {}

func (x *PeersAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeersAddRequest.ProtoReflect.Descriptor instead.
func (*PeersAddRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_system_proto_rawDescGZIP(), []int{2}
}

func (x *PeersAddRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PeersAddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeersAddResponse) Reset() {
	*x = PeersAddResponse{}
	mi := &file_server_proto_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeersAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeersAddResponse) ProtoMessage() {}

func (x *PeersAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeersAddResponse.ProtoReflect.Descriptor instead.
func (*PeersAddResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_system_proto_rawDescGZIP(), []int{3}
}

func (x *PeersAddResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PeersStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeersStatusRequest) Reset() {
	*x = PeersStatusRequest{}
	mi := &file_server_proto_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeersStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeersStatusRequest) ProtoMessage() {}

func (x *PeersStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeersStatusRequest.ProtoReflect.Descriptor instead.
func (*PeersStatusRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_system_proto_rawDescGZIP(), []int{4}
}

func (x *PeersStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PeersListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*Peer                `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeersListResponse) Reset() {
	*x = PeersListResponse{}
	mi := &file_server_proto_system_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeersListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeersListResponse) ProtoMessage() {}

func (x *PeersListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_system_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeersListResponse.ProtoReflect.Descriptor instead.
func (*PeersListResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_system_proto_rawDescGZIP(), []int{5}
}

func (x *PeersListResponse) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type BlockByNumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        uint64                 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockByNumberRequest) Reset() {
	*x = BlockByNumberRequest{}
	mi := &file_server_proto_system_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockByNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockByNumberRequest) ProtoMessage() {}

func (x *BlockByNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_system_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockByNumberRequest.ProtoReflect.Descriptor instead.
func (*BlockByNumberRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_system_proto_rawDescGZIP(), []int{6}
}

func (x *BlockByNumberRequest) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type BlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockResponse) Reset() {
	*x = BlockResponse{}
	mi := &file_server_proto_system_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockResponse) ProtoMessage() {}

func (x *BlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_system_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockResponse.ProtoReflect.Descriptor instead.
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_system_proto_rawDescGZIP(), []int{7}
}

func (x *BlockResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type HealthResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ChainIds           []int64                `protobuf:"varint,1,rep,packed,name=chain_ids,json=chainIds,proto3" json:"chain_ids,omitempty"`
	BlockHeight        uint64                 `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	CurrentSubscribers uint64                 `protobuf:"varint,3,opt,name=current_subscribers,json=currentSubscribers,proto3" json:"current_subscribers,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_server_proto_system_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_system_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_system_proto_rawDescGZIP(), []int{8}
}

func (x *HealthResponse) GetChainIds() []int64 {
	if x != nil {
		return x.ChainIds
	}
	return nil
}

func (x *HealthResponse) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *HealthResponse) GetCurrentSubscribers() uint64 {
	if x != nil {
		return x.CurrentSubscribers
	}
	return 0
}

var File_server_proto_system_proto protoreflect.FileDescriptor

const file_server_proto_system_proto_rawDesc = "" +
	"\n" +
	"\x19server/proto/system.proto\x12\x02v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"(\n" +
	"\fServerStatus\x12\x18\n" +
	"\ap2pAddr\x18\x01 \x01(\tR\ap2pAddr\"J\n" +
	"\x04Peer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tprotocols\x18\x02 \x03(\tR\tprotocols\x12\x14\n" +
	"\x05addrs\x18\x03 \x03(\tR\x05addrs\"!\n" +
	"\x0fPeersAddRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\",\n" +
	"\x10PeersAddResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"$\n" +
	"\x12PeersStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x11PeersListResponse\x12\x1e\n" +
	"\x05peers\x18\x01 \x03(\v2\b.v1.PeerR\x05peers\".\n" +
	"\x14BlockByNumberRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\"#\n" +
	"\rBlockResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x81\x01\n" +
	"\x0eHealthResponse\x12\x1b\n" +
	"\tchain_ids\x18\x01 \x03(\x03R\bchainIds\x12!\n" +
	"\fblock_height\x18\x02 \x01(\x04R\vblockHeight\x12/\n" +
	"\x13current_subscribers\x18\x03 \x01(\x04R\x12currentSubscribers2\xf3\x02\n" +
	"\x06System\x12F\n" +
	"\tGetStatus\x12\x16.google.protobuf.Empty\x1a\x10.v1.ServerStatus\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/status\x12H\n" +
	"\bPeersAdd\x12\x13.v1.PeersAddRequest\x1a\x14.v1.PeersAddResponse\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/peers\x12J\n" +
	"\tPeersList\x12\x16.google.protobuf.Empty\x1a\x15.v1.PeersListResponse\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/peers\x12D\n" +
	"\vPeersStatus\x12\x16.v1.PeersStatusRequest\x1a\b.v1.Peer\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/peers/{id}\x12E\n" +
	"\x06Health\x12\x16.google.protobuf.Empty\x1a\x12.v1.HealthResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/healthB\x0fZ\r/server/protob\x06proto3"

var (
	file_server_proto_system_proto_rawDescOnce sync.Once
	file_server_proto_system_proto_rawDescData []byte
)

func file_server_proto_system_proto_rawDescGZIP() []byte {
	file_server_proto_system_proto_rawDescOnce.Do(func() {
		file_server_proto_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_system_proto_rawDesc), len(file_server_proto_system_proto_rawDesc)))
	})
	return file_server_proto_system_proto_rawDescData
}

var file_server_proto_system_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_server_proto_system_proto_goTypes = []any{
	(*ServerStatus)(nil),         // 0: v1.ServerStatus
	(*Peer)(nil),                 // 1: v1.Peer
	(*PeersAddRequest)(nil),      // 2: v1.PeersAddRequest
	(*PeersAddResponse)(nil),     // 3: v1.PeersAddResponse
	(*PeersStatusRequest)(nil),   // 4: v1.PeersStatusRequest
	(*PeersListResponse)(nil),    // 5: v1.PeersListResponse
	(*BlockByNumberRequest)(nil), // 6: v1.BlockByNumberRequest
	(*BlockResponse)(nil),        // 7: v1.BlockResponse
	(*HealthResponse)(nil),       // 8: v1.HealthResponse
	(*emptypb.Empty)(nil),        // 9: google.protobuf.Empty
}
var file_server_proto_system_proto_depIdxs = []int32{
	1, // 0: v1.PeersListResponse.peers:type_name -> v1.Peer
	9, // 1: v1.System.GetStatus:input_type -> google.protobuf.Empty
	2, // 2: v1.System.PeersAdd:input_type -> v1.PeersAddRequest
	9, // 3: v1.System.PeersList:input_type -> google.protobuf.Empty
	4, // 4: v1.System.PeersStatus:input_type -> v1.PeersStatusRequest
	9, // 5: v1.System.Health:input_type -> google.protobuf.Empty
	0, // 6: v1.System.GetStatus:output_type -> v1.ServerStatus
	3, // 7: v1.System.PeersAdd:output_type -> v1.PeersAddResponse
	5, // 8: v1.System.PeersList:output_type -> v1.PeersListResponse
	1, // 9: v1.System.PeersStatus:output_type -> v1.Peer
	8, // 10: v1.System.Health:output_type -> v1.HealthResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_server_proto_system_proto_init() }
func file_server_proto_system_proto_init() {
	if File_server_proto_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_system_proto_rawDesc), len(file_server_proto_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_system_proto_goTypes,
		DependencyIndexes: file_server_proto_system_proto_depIdxs,
		MessageInfos:      file_server_proto_system_proto_msgTypes,
	}.Build()
	File_server_proto_system_proto = out.File
	file_server_proto_system_proto_goTypes = nil
	file_server_proto_system_proto_depIdxs = nil
}
